name: Add issue to project

on:
  issues:
    types: [opened]

permissions: {}

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.PROJECT_HANDLER_BOT_APP_ID }}
          private-key: ${{ secrets.PROJECT_HANDLER_BOT_PEM }}
          owner: ${{ github.repository_owner }}

      - uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: https://github.com/orgs/datasciencecampus/projects/194
          github-token: ${{ steps.app-token.outputs.token }}
