name: Add Pull Request To Projects

on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  add-pr-to-projects:
    uses: datasciencecampus/github-actions/.github/workflows/add-pr-to-projects.yml@d4300bbb5419327046686baa55f394ff309db2f0 # v1.2.2
    secrets:
      PROJECT_ROUTER_BOT_PRIVATE_KEY: ${{ secrets.PROJECT_ROUTER_BOT_PRIVATE_KEY }}
    with:
      repository: ${{ github.event.repository.name }}
      pull_request_node_id: ${{ github.event.pull_request.node_id }}
      project_field_values: '[{"project":194,"field":"Status","value":"Review"}]'
